
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 09 21:19:35 BRT 2018
//----------------------------------------------------

package compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONSTANT = 7;
  public static final int RELOP = 4;
  public static final int ADDOP = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int MULOP = 2;
  public static final int PARENTHESE_LEFT = 5;
  public static final int IDENTIFIER = 8;
  public static final int PARENTHESE_RIGHT = 6;
}

